CREATE DATABASE ecom_db;

DROP TABLE candidate;
CREATE TABLE candidate(
id INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
email_id VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL,
active TINYINT NOT NULL DEFAULT 1
);

DROP TABLE medicine;
CREATE TABLE medicine(
id INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
mfg_date DATE NOT NULL,
exp_date DATE NOT NULL,
batch_no INT NOT NULL,
cost DECIMAL NOT NULL,
category VARCHAR(50) NOT NULL,
active TINYINT NOT NULL DEFAULT 1
);

DROP TABLE orders;
CREATE TABLE orders(
id INT PRIMARY KEY AUTO_INCREMENT,
candidate_id INT NOT NULL,
medicine_id INT NOT NULL,
qty INT NOT NULL,
total_cost DECIMAL NOT NULL,
order_date DATE,
STATUS VARCHAR(50) DEFAULT 'ORDERED',
CONSTRAINT candidate_id_fk FOREIGN KEY (candidate_id) REFERENCES CANDIDATE(id),
CONSTRAINT medicine_id_fk FOREIGN KEY (medicine_id) REFERENCES MEDICINE(id)
);

